swagger: '2.0'
info:
  version: 0.1.0
  title: Simple Address API 
consumes:
  - application/joinc.user-address.v1+json
produces:
  - application/joinc.user-address.v1+json
schemes:
  - http
paths:
  '/user/{id}':
    get:
      summary: 유저 정보를 읽어온다.
      tags:
        - user 
      parameters:
        - name: id
          type: string 
          in: path 
          required: true
      responses:
        '200':
          description: OK 
          schema:
            $ref: "#/definitions/user"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  '/search':
    get: 
      summary: user_id로 유저를 검색한다.
      consumes:
        - application/json
      tags:
        - user 
      parameters:
        - name: body 
          in: body 
          description: user id
          schema:
            $ref: "#/definitions/user"
      responses:
        '200':
          description: OK 
          schema:
            $ref: "#/definitions/user"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  user:
    type: object
    required:
      - user_id
    properties:
      user_id:
        type: string 
        description: user id
      name:
        type: string
        description: user name
      address:
        type: string
        description: user address 
      email:
        type: string
        description: user email 
  error:
    type: object
    properties:
      message:
        type: string
        description: error message
      code:
        type: integer 
        description: error code 
